import type { GuideModule } from "./types";

function crudScreens(
  base: string,
  entity: string,
  listRoute: string,
  newRoute: string,
  detailRoute: string,
  editRoute: string,
  previewEntity: string,
): GuideModule["screens"] {
  const lower = entity.toLowerCase();
  return [
    {
      id: `${base}-list`,
      title: `${entity} list`,
      route: listRoute,
      permission: "view",
      summary: `Browse all ${lower}s with search, filters, and pagination.`,
      steps: [
        `Open **${entity}** from the sidebar.`,
        `Use the search box to find a ${lower} by name, code, or contact details.`,
        `Apply date or category filters if available, then review the table results.`,
        `Click a row or the **View** (eye) icon to open details.`,
      ],
      tips: [`Export options appear when you have view access and data is loaded.`],
      preview: "list",
    },
    {
      id: `${base}-create`,
      title: `Create ${lower}`,
      route: newRoute,
      permission: "add",
      summary: `Add a new ${lower} with required fields and save.`,
      steps: [
        `From the ${entity} list, click **Add ${entity}** or **New ${entity}**.`,
        `Fill in all required fields marked on the form (name, contact, branch, etc.).`,
        `Review entries for typos before saving.`,
        `Click **Save** — you will return to the list with the new ${lower} visible.`,
      ],
      tips: [`Duplicate names or mobile numbers may show a validation error from the server.`],
      preview: "form",
    },
    {
      id: `${base}-detail`,
      title: `${entity} details`,
      route: detailRoute,
      permission: "view",
      summary: `View full information for a single ${lower}.`,
      steps: [
        `Open a ${lower} from the list by clicking its row or the view icon.`,
        `Review all sections: basic info, linked records, and status badges.`,
        `Use action buttons at the top only if your role allows edit or delete.`,
      ],
      preview: "detail",
    },
    {
      id: `${base}-edit`,
      title: `Edit ${lower}`,
      route: editRoute,
      permission: "edit",
      summary: `Update an existing ${lower}'s details.`,
      steps: [
        `Open the ${lower} detail page or click **Edit** from the list.`,
        `Change the fields you need — unchanged fields stay as they were.`,
        `Click **Save** to apply updates.`,
      ],
      tips: [`Some records lock editing after a certain status (e.g. delivered orders).`],
      preview: "form",
    },
    {
      id: `${base}-delete`,
      title: `Delete ${lower}`,
      route: listRoute,
      permission: "delete",
      summary: `Remove a ${lower} after confirmation.`,
      steps: [
        `From the list or detail page, click **Delete** (trash icon).`,
        `Read the confirmation dialog — deletion is usually permanent.`,
        `Confirm only if you are sure; linked records may block deletion.`,
      ],
      tips: [`If delete is disabled, the record may be in use elsewhere in the system.`],
      preview: "list",
    },
  ];
}

/** Staff ERP user guide content — filtered at runtime by role permissions. */
export const STAFF_GUIDE_MODULES: GuideModule[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    section: "Menu",
    audience: "staff",
    intro: "Your home screen shows KPIs, charts, and quick insights for the selected branch.",
    screens: [
      {
        id: "dashboard-overview",
        title: "Dashboard overview",
        route: "/dashboard",
        permission: "view",
        summary: "See revenue, orders, inventory alerts, and category charts at a glance.",
        steps: [
          "Select your branch from the header picker (if you have access to multiple branches).",
          "Review KPI cards at the top: revenue, pending orders, low stock, and more.",
          "Scroll through chart cards to compare categories, sources, and forecasts.",
          "Click chart segments or summary links to jump to related modules (e.g. Orders).",
        ],
        tips: ["Data refreshes when you change the branch or reload the page."],
        preview: "dashboard",
      },
    ],
  },
  {
    key: "purchaseOrders",
    label: "Purchase orders",
    icon: "ClipboardList",
    section: "Menu",
    audience: "staff",
    intro: "Create and track purchase orders sent to suppliers and manufacturers.",
    screens: [
      {
        id: "po-list",
        title: "Purchase orders list",
        route: "/purchase-orders",
        permission: "view",
        summary: "Browse all purchase orders with search, filters, and pagination.",
        steps: [
          "Open **Purchase orders** from the sidebar.",
          "Use search to find a PO by number or supplier name.",
          "Filter by status and review the table results.",
          "Click a row to open PO details.",
        ],
        preview: "list",
      },
      {
        id: "po-create",
        title: "Create purchase order",
        route: "/purchase-orders",
        permission: "add",
        summary:
          "Raise a PO from the list dialog: choose supplier or manufacturer, add catalog/custom line items with product & variant selection, then set delivery date.",
        steps: [
          "Select your **branch** in the header — PO is created for that branch.",
          "On **Purchase orders** list, click **Create PO** to open the dialog.",
          "Choose **PO Type**: **Supplier (Ready Goods)** or **Manufacturer (Custom)**.",
          "Pick the **Supplier** or **Manufacturer** from the dropdown (required).",
          "In **Items**, choose **From catalog** (product from your catalog) or **Custom (this PO only)** (one-off line not saved to catalog).",
          "For catalog lines: open **Product**, search by name/SKU, and select. If the product has variants, you **must** pick a **Variant** — price fills from the variant.",
          "Set **Quantity**, **Unit price (₹)**, and optional **Description** for each line. Click **Add item** for more rows; trash removes a row (at least one required).",
          "Set **Expected Delivery Date** (today or later).",
          "Click **Create PO** — the PO appears in the list with status Pending.",
        ],
        tips: [
          "PO line items use the same product picker as sales orders, but stock is not enforced on POs.",
          "Custom lines let you describe bespoke items without adding them to the product catalog.",
        ],
        stepHighlights: [
          "branch-picker",
          "form-header",
          "po-type",
          "po-vendor",
          "line-item-mode",
          "product-select",
          "line-qty-price",
          "expected-delivery",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "po-detail",
        title: "Purchase order details",
        route: "/purchase-orders/1042",
        permission: "view",
        summary: "Track PO from draft through supplier confirmation and receipt.",
        steps: [
          "Open a PO to see its current status badge (Draft, Sent, Confirmed, etc.).",
          "Review line items, totals, and linked complaints if any.",
          "Use edit actions to update quantities or status when permitted.",
        ],
        preview: "detail",
      },
      {
        id: "po-edit",
        title: "Edit purchase order",
        route: "/purchase-orders/1042/edit",
        permission: "edit",
        summary:
          "Full-page edit form — same fields as create: vendor, line items with product/variant picker, delivery date, and notes.",
        steps: [
          "Open the PO detail page and click **Edit**, or go to `/purchase-orders/{id}/edit`.",
          "Update **PO Type** and **Supplier/Manufacturer** if the vendor changed.",
          "In **Items**, add/remove lines with **Add item** or the trash icon (minimum one line).",
          "For each line use **From catalog** + **Product** + **Variant** (when applicable), or switch to **Custom (this PO only)** for one-off descriptions.",
          "Adjust **Quantity** and **Unit price** — totals recalculate on save.",
          "Change **Expected Delivery Date** and **Notes** for the vendor.",
          "Click **Save changes** — you return to the PO detail page.",
        ],
        tips: ["Some statuses may limit what partners can change from the supplier portal."],
        stepHighlights: [
          "form-header",
          "po-vendor",
          "order-items-section",
          "product-select",
          "line-qty-price",
          "expected-delivery",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "po-delete",
        title: "Delete purchase order",
        route: "/purchase-orders",
        permission: "delete",
        summary: "Remove a PO after confirmation.",
        steps: [
          "From the list or detail page, click **Delete**.",
          "Confirm in the dialog — sent or confirmed POs may be restricted.",
        ],
        preview: "list",
      },
    ],
  },
  {
    key: "orders",
    label: "Orders",
    icon: "ShoppingCart",
    section: "Orders",
    audience: "staff",
    intro: "Manage sales orders from quotation through delivery and payment.",
    screens: [
      {
        id: "orders-list",
        title: "Orders list",
        route: "/orders",
        permission: "view",
        summary: "Search and filter sales orders by status, payment, GST, and date.",
        steps: [
          "Open **Orders** from the sidebar.",
          "Use search for order number, customer name, or mobile.",
          "Filter by status (Pending, Confirmed, Delivered), payment status, or GST type.",
          "Click a row to open order details.",
        ],
        tips: ["Assignment scope filters show only orders you created or are assigned to, based on your role."],
        preview: "list",
      },
      {
        id: "orders-create",
        title: "Create order",
        route: "/orders/new",
        permission: "add",
        summary:
          "Full order form: customer details, GST, line items with catalog product/variant picker (stock-aware), payment sidebar, and required challan photo.",
        steps: [
          "Select your **branch** in the header — stock checks and assignees use this branch.",
          "From **Orders** list click **Create Order**, or open `/orders/new`.",
          "Fill **Order details**: **Customer Name***, **Mobile***, optional **Address** (Google search), and **Assign to (team)**.",
          "Set **GST Invoice** to Yes or No. If Yes, enter **GST Number*** — unit prices on lines are treated as GST-inclusive.",
          "In **Order items**, pick **From catalog** (default) or **Custom (this order only)** for a one-off product not in catalog.",
          "**From catalog**: click **Product**, search and select. If the product has variants, select **Variant** (required). Out-of-stock products at your branch cannot be selected.",
          "Set **Quantity** (capped by branch stock when shown) and **Unit price**. Price auto-fills from product/variant but can be edited. Add optional **Description**.",
          "Click **Add item** for multiple products; use trash to remove a line (keep at least one).",
          "Optional: **Order category**, **Delivery** (charge, driver, date, delivery assignees).",
          "Right column: review **Payment summary**, set **Payment status**, **Mode**, and **Advance amount**.",
          "Upload a **Challan** photo (required) under **Challan & photos**, then click **Create order**.",
        ],
        tips: [
          "Custom lines capture name, size, colour, fabric, and photos — they do not add a catalog product.",
          "Advance amount cannot exceed the order total shown in Payment summary.",
        ],
        stepHighlights: [
          "branch-picker",
          "form-header",
          "order-details",
          "gst-section",
          "line-item-mode",
          "product-select",
          "line-qty-price",
          "add-item",
          "delivery-section",
          "payment-sidebar",
          "challan-section",
        ],
        preview: "form",
      },
      {
        id: "orders-detail",
        title: "Order details",
        route: "/orders/1042",
        permission: "view",
        summary: "View full order: items, payments, delivery, and invoices.",
        steps: [
          "Open an order from the list.",
          "Review line items, totals, payment status, and delivery information.",
          "Check linked invoices and payment records in their tabs or sections.",
        ],
        preview: "detail",
      },
      {
        id: "orders-edit",
        title: "Edit order",
        route: "/orders/1042/edit",
        permission: "edit",
        summary:
          "Same layout as create — update customer, line items, delivery, payment, and challan. Locked after delivery/complete.",
        steps: [
          "Open order detail and click **Edit**, or use the edit icon on the orders list (hidden if order is locked).",
          "Update **Order details** and **Order status** (edit mode only). GST and customer fields work the same as create.",
          "Change line items: switch **From catalog** / **Custom**, re-pick **Product** and **Variant**, adjust **Quantity** and **Unit price**.",
          "Use **Add item** or trash to add/remove lines — stock limits still apply for catalog items.",
          "Update **Delivery** and **Payment** sections on the right; paid/balance amounts reflect existing payments.",
          "Replace **Challan** if needed, then click **Save changes**.",
        ],
        tips: [
          "Orders lock when delivered or complete — you will be redirected to the detail page instead of edit.",
          "Partially paid orders keep recorded payments; changing totals may affect due balance.",
        ],
        stepHighlights: [
          "form-header",
          "order-details",
          "order-items-section",
          "line-item-mode",
          "product-select",
          "line-qty-price",
          "add-item",
          "payment-sidebar",
          "challan-section",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "orders-delete",
        title: "Delete order",
        route: "/orders",
        permission: "delete",
        summary: "Remove an order after typing confirmation.",
        steps: [
          "Select one or more orders using checkboxes, or use delete on a single row.",
          "Click **Delete** and type the confirmation text shown in the dialog.",
          "Confirm — this action cannot be undone.",
        ],
        preview: "list",
      },
    ],
  },
  {
    key: "deliveries",
    label: "Deliveries",
    icon: "CalendarClock",
    section: "Orders",
    audience: "staff",
    intro:
      "Plan customer deliveries: set delivery dates on orders, track the booked schedule by day, assign drivers, update delivery status, and manage driver records.",
    screens: [
      {
        id: "deliveries-calendar",
        title: "Booked deliveries",
        route: "/deliveries",
        permission: "view",
        summary:
          "Open Delivery Management → **Booked deliveries** tab. Orders with a delivery date appear grouped by day; filter by date range and open any order.",
        steps: [
          "Select your **branch** in the header — the schedule shows deliveries for that branch only.",
          "Open **Deliveries** from the sidebar (Orders section). The page title is **Delivery Management**.",
          "Stay on the **Booked deliveries** tab (default). The card title reads **Delevery Schedule**.",
          "Use the **date range filter** (top right of the card) to narrow which delivery days appear.",
          "Scroll the list — each **date heading** groups orders due that day with order count.",
          "Each row shows **order number**, customer, mobile, delivery charge, **driver** dropdown, **delivery status**, and a **view** (eye) icon.",
          "Click the **eye** icon to open the full order detail page.",
        ],
        tips: [
          "You need **Orders → View** permission to see booked deliveries in the list.",
          "If the list is empty, orders may not have a delivery date set yet — schedule them from the order form.",
        ],
        stepHighlights: [
          "branch-picker",
          "page-header",
          "delivery-tabs",
          "delivery-date-filter",
          "delivery-schedule-list",
          "delivery-schedule-list",
          "order-view-link",
        ],
        preview: "list",
      },
      {
        id: "deliveries-schedule",
        title: "Schedule a delivery",
        route: "/orders/new",
        permission: "add",
        summary:
          "Set a delivery date and driver when creating or editing an order — the order then appears under Booked deliveries.",
        steps: [
          "Select your **branch** in the header before creating the order.",
          "Open **Create order** (`/orders/new`) or **Edit order** for an existing order.",
          "Scroll to the **Delivery** section on the order form (below order line items).",
          "Pick a **Delivery date** — this is when the customer expects delivery.",
          "Choose a **Driver** from the dropdown (drivers must be added under Deliveries → Drivers first).",
          "Optionally set **Delivery charge (₹)** and **Delivery assignees** (staff).",
          "Click **Create order** or **Save changes** — the order appears on **Deliveries → Booked deliveries** for that date.",
        ],
        tips: [
          "Delivery time slots are optional — when enabled, a slot picker appears on the order form.",
          "Driver assignment can also be done later from the Booked deliveries list.",
        ],
        stepHighlights: [
          "branch-picker",
          "page-header",
          "delivery-section",
          "delivery-date-field",
          "delivery-driver-field",
          "delivery-section",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "deliveries-update",
        title: "Update delivery status & driver",
        route: "/deliveries",
        permission: "edit",
        summary:
          "From the Booked deliveries tab, change delivery status (Pending → Out for delivery → Delivered) or reassign the driver without opening the order form.",
        steps: [
          "Open **Deliveries** and select the correct **branch**.",
          "On **Booked deliveries**, use the date filter to find the delivery day.",
          "Locate the order row in the schedule list for that date.",
          "Use the **Assign driver** dropdown to pick or change the driver (requires **Deliveries → Edit**).",
          "Use the **Delivery status** dropdown to move the order through **Pending**, **Out for delivery**, or **Delivered**.",
          "Changes save immediately — no separate Save button on this screen.",
          "Use the **eye** icon if you need to edit delivery date or charge on the full order form.",
        ],
        tips: [
          "Users with **Orders → Edit** can also update delivery status from the Orders list.",
          "Updating status here does not change the sales order status (Order Received, Complete, etc.).",
        ],
        stepHighlights: [
          "branch-picker",
          "page-header",
          "delivery-date-filter",
          "delivery-schedule-list",
          "driver-assign",
          "delivery-status",
          "order-view-link",
        ],
        preview: "list",
      },
      {
        id: "deliveries-cancel",
        title: "Cancel / unschedule a delivery",
        route: "/orders/1042/edit",
        permission: "edit",
        summary:
          "Remove a delivery booking by clearing the delivery date (and driver) on the order edit form, then saving.",
        steps: [
          "Open the order from **Booked deliveries** (eye icon) or the **Orders** list.",
          "Click **Edit order** (or use the edit icon on the orders list).",
          "Scroll to the **Delivery** section on the edit form.",
          "Clear the **Delivery date** field to unschedule — the order drops off the booked deliveries list.",
          "Clear the **Driver** field if you want to remove the assignment as well.",
          "Read the reminder that clearing date removes the booking, then click **Save changes**.",
        ],
        tips: [
          "This does not delete the sales order — only the scheduled delivery date.",
          "When delivery time slots are enabled, clearing the slot on the order also frees capacity.",
        ],
        stepHighlights: [
          "page-header",
          "delivery-section",
          "delivery-date-field",
          "delivery-driver-field",
          "clear-delivery",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "drivers-list",
        title: "Drivers list",
        route: "/drivers",
        permission: "view",
        summary:
          "Manage delivery drivers for the branch: add, search, edit, and open driver profiles. Also reachable via Deliveries → Drivers tab → Manage drivers.",
        steps: [
          "Select your **branch** in the header.",
          "Open **Drivers** from the sidebar, or go to **Deliveries → Drivers** tab and click **Manage drivers**.",
          "Use **Search drivers…** to find by name, mobile, or vehicle details.",
          "Review the table: **Driver**, **Vehicle**, **Deliveries**, **Payments**, and action icons.",
          "Click **Add driver** to create a new driver (requires **Deliveries → Add**).",
          "Click the **eye** icon on a row to open the driver detail page.",
          "Use **pencil** to edit or **trash** to deactivate a driver when permitted.",
        ],
        stepHighlights: [
          "branch-picker",
          "page-header",
          "search",
          "data-table",
          "header-action-add",
          "table-actions",
          "table-actions",
        ],
        preview: "list",
      },
      {
        id: "drivers-detail",
        title: "Driver details",
        route: "/drivers/12",
        permission: "view",
        summary:
          "View a driver's assigned deliveries, delivery charges, payment history, and record new driver payments.",
        steps: [
          "Open a driver from the **Drivers** list (eye icon).",
          "Review the header: driver **name**, **mobile**, and **vehicle** info.",
          "The **Deliveries** table lists orders assigned to this driver with date, status, and charge.",
          "Click an **order number** link to open that order.",
          "Scroll to **Payment history** for past payments recorded for this driver.",
          "The sidebar **Payment summary** shows total charges, paid, and due amounts.",
          "Use **Record payment** (if you have add permission) to log cash/UPI/bank payments to the driver.",
        ],
        stepHighlights: [
          "detail-header",
          "driver-deliveries-table",
          "driver-deliveries-table",
          "driver-deliveries-table",
          "payment-history",
          "payment-summary",
          "record-payment",
        ],
        preview: "detail",
      },
    ],
  },
  {
    key: "products",
    label: "Products",
    icon: "Package",
    section: "Products",
    audience: "staff",
    intro:
      "Build and maintain your catalog: product list with filters, create/edit forms with variants & photos, and a detail page for stock, pricing, and variations.",
    screens: [
      {
        id: "products-list",
        title: "Products list",
        route: "/products",
        permission: "view",
        summary:
          "Browse the catalog with search, date range, category, and low-stock filters. Stock column reflects the branch selected in the header.",
        steps: [
          "Open **Products** from the sidebar (Products section).",
          "Review the page title **Products** and subtitle about catalog and variants.",
          "Use **Search products…** to find by name, SKU, or description.",
          "Filter with **Date range**, **Category**, or toggle **Low stock only** to narrow results.",
          "Scan the table: **Name** (with thumbnail), **SKU**, **Category**, **Price**, **GST**, **Stock**, **Variants**.",
          "Click **Add Product** to create a new catalog item (requires **Products → Add**).",
          "Use row icons: **View** (eye), **Edit** (pencil), **Delete** (trash) when your role allows.",
        ],
        tips: [
          "Stock numbers use the branch from the header — switch branch to see branch-specific stock.",
          "Products with variants show a price range and a **Variants (n)** pill linking to the detail page.",
        ],
        stepHighlights: [
          "page-header",
          "search",
          "filters",
          "data-table",
          "header-action-add",
          "table-actions",
          "table-actions",
        ],
        preview: "list",
      },
      {
        id: "products-create",
        title: "Create product",
        route: "/products/new",
        permission: "add",
        summary:
          "Full-page form: product details, inventory type (single SKU vs variants), photos, pricing thresholds, and GST note.",
        steps: [
          "From the products list, click **Add Product** or open `/products/new`.",
          "Use the header **Create product** bar — **Cancel** or **Create product** when done.",
          "Fill **Product details**: name, **Category** (main + sub), **SKU**, optional description.",
          "Choose **Inventory type**: **Single SKU** (one price/stock) or **Has variants** (colors, sizes, etc.).",
          "If variants: click **Add variant** and fill name, SKU, price, photos, and attributes per row.",
          "Upload **Product photos** in the right column (catalog gallery).",
          "Set **Pricing & stock** or **Stock alerts** — low-stock threshold; actual quantity is updated in **Inventory**.",
          "Review the **GST** note (default % from Settings), then click **Create product**.",
        ],
        tips: [
          "Variant products can start with zero variants — add more later from the product detail page.",
          "Category uses main + sub-category pickers with optional inline category management.",
        ],
        stepHighlights: [
          "form-header",
          "product-details",
          "inventory-type",
          "variants-section",
          "product-photos",
          "pricing-stock",
          "gst-info",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "products-detail",
        title: "Product details",
        route: "/products/501",
        permission: "view",
        summary:
          "Gallery, stock/pricing stats, description, and variations table — add or manage variants from here.",
        steps: [
          "Open a product from the list (click name, eye icon, or **Variants** pill).",
          "Review the header: product **name**, **category** path, and **Active** status.",
          "Left column: **Photo gallery** and stats card (**Total units**, **Variations**, GST, SKU, price range).",
          "Read the **Description** section on the right (Show more if text is long).",
          "For variant products, use the **Variations** table — stock, price, and status per row.",
          "Click **Edit** to change catalog fields, or **Add variation** to create a new variant inline.",
          "Use the **⋮** menu → **Delete product** to remove the product and all variants (with confirmation).",
        ],
        tips: [
          "Single-SKU products show a **Variables** card (size, colour, fabric) instead of a variations table.",
          "Stock totals respect the branch selected in the header, with per-branch breakdown when available.",
        ],
        stepHighlights: [
          "detail-header",
          "product-gallery",
          "product-stats",
          "product-description",
          "variants-table",
          "detail-edit-btn",
          "delete-action",
        ],
        preview: "detail",
      },
      {
        id: "products-edit",
        title: "Edit product",
        route: "/products/501/edit",
        permission: "edit",
        summary: "Same layout as create — update details, switch inventory type, manage variants, photos, and thresholds.",
        steps: [
          "From product detail click **Edit**, or use the pencil icon on the products list — the **Edit product** header loads existing values.",
          "Update **Product details** (name, category, SKU, description) as needed.",
          "Change **Inventory type** only if you understand variant implications — existing stock may be affected.",
          "Manage **Variants**: add rows with **Add variant**, edit fields, or remove with trash.",
          "Replace or add **Product photos** in the sidebar.",
          "Adjust **Pricing & stock** / **Stock alerts** thresholds — quantity still comes from Inventory.",
          "Click **Save changes** — you return to the product detail page.",
        ],
        stepHighlights: [
          "form-header",
          "product-details",
          "inventory-type",
          "variants-section",
          "product-photos",
          "pricing-stock",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "products-delete",
        title: "Delete product",
        route: "/products",
        permission: "delete",
        summary: "Remove a product and all its variants from the catalog after browser confirmation.",
        steps: [
          "Open **Products** and find the item using search or filters.",
          "Click the red **trash** icon on the product row (requires **Products → Delete**).",
          "Read the confirmation: **Delete this product and all its variants?**",
          "Confirm only if the product is not needed — linked orders keep historical line data but the catalog entry is gone.",
        ],
        stepHighlights: ["page-header", "data-table", "delete-action", "delete-dialog"],
        preview: "list",
      },
    ],
  },
  {
    key: "categories",
    label: "Categories",
    icon: "Tags",
    section: "Products",
    audience: "staff",
    intro:
      "Organize your catalog with a two-level hierarchy: **main categories** (e.g. Living Room) and **subcategories** under them (e.g. Sofas). Categories appear in product forms, filters, and reports.",
    screens: [
      {
        id: "categories-list",
        title: "Categories list",
        route: "/categories",
        permission: "view",
        summary:
          "Single-page view of all main and sub categories in a tree-style table — type badges, parent name, and subcategory counts.",
        steps: [
          "Open **Categories** from the sidebar (Products section).",
          "Read the page header — main categories must be created before subcategories.",
          "Use **Add main category** or **Add subcategory** in the header when you have add/edit permission.",
          "Scan the table: indented **Name** (└ for subcategories), **Type** badge, **Parent**, **Subcategories** count on main rows.",
          "On each main category row, **Add sub** quickly opens the subcategory dialog with that parent pre-selected.",
          "Use **Edit** (pencil) or **Delete** (trash) on any row when your role allows.",
        ],
        tips: [
          "**Add subcategory** stays disabled until at least one main category exists.",
          "Subcategories inherit their parent in product pickers — products use main + sub selection.",
        ],
        stepHighlights: [
          "page-header",
          "page-header",
          "header-action-add-main",
          "data-table",
          "table-actions",
          "table-actions",
        ],
        preview: "list",
      },
      {
        id: "categories-add-main",
        title: "Add main category",
        route: "/categories",
        permission: "add",
        summary: "Create a top-level category via dialog — no parent required.",
        steps: [
          "On the categories page, click **Add main category** (primary button in the header).",
          "The **Add main category** dialog opens with title and short description.",
          "Enter **Main category name** — e.g. Living Room, Bedroom, Dining.",
          "Note the info box: this will be a **main (top-level)** category (no parent field).",
          "Click **Create main category** — the list refreshes and the new row appears at top level.",
          "Cancel closes the dialog without saving.",
        ],
        tips: [
          "Create all main categories first — subcategories and the **Add subcategory** button depend on them.",
          "Main category names should be broad groupings; use subcategories for specific product types.",
        ],
        stepHighlights: [
          "header-action-add-main",
          "category-dialog",
          "category-name",
          "main-category-note",
          "form-save",
          "form-cancel",
        ],
        preview: "form",
      },
      {
        id: "categories-add-sub",
        title: "Add subcategory",
        route: "/categories",
        permission: "add",
        summary: "Add a child category under an existing main category — from header or row **Add sub**.",
        steps: [
          "Click **Add subcategory** in the header, or **Add sub** on a main category row (pre-fills parent).",
          "The **Add subcategory** dialog opens — subcategories always belong to one main category.",
          "Enter **Name** — e.g. Sofas, Coffee Tables, Beds.",
          "Select **Main category *** from the dropdown (required). Header button defaults to the first main category.",
          "Click **Create subcategory** — the new row appears indented under its parent in the table.",
          "If no main categories exist, the parent dropdown is empty and save stays disabled.",
        ],
        tips: [
          "You cannot add a subcategory until at least one main category exists.",
          "Product forms show main + sub pickers — both levels must exist before assigning products.",
        ],
        stepHighlights: [
          "header-action-add-sub",
          "category-dialog",
          "category-name",
          "parent-category",
          "form-save",
          "parent-category",
        ],
        preview: "form",
      },
      {
        id: "categories-edit",
        title: "Edit category",
        route: "/categories",
        permission: "edit",
        summary: "Rename a category or move a subcategory to another main parent — same dialog for main and sub.",
        steps: [
          "Click the **Edit** (pencil) icon on any category row.",
          "Dialog title shows **Edit main category** or **Edit subcategory** based on the row type.",
          "Update **Name** — validation follows category name rules.",
          "For subcategories: change **Main category *** to move under a different parent.",
          "If a main category still has subcategories, its parent field is locked — remove children first before moving.",
          "Click **Save changes** — the table updates; cancel discards edits.",
        ],
        tips: [
          "Editing a main category name updates it everywhere — product filters, reports, and pickers.",
          "Moving a subcategory reassigns all products linked to that sub under the new main parent path.",
        ],
        stepHighlights: [
          "table-actions",
          "category-dialog",
          "category-name",
          "parent-category",
          "parent-category",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "categories-delete",
        title: "Delete category",
        route: "/categories",
        permission: "delete",
        summary: "Remove a category after clearing subcategories and reassigning products.",
        steps: [
          "Click the red **Delete** (trash) icon on a category row.",
          "Read **Delete category?** — shows the category name being removed.",
          "If the category has subcategories, a red warning lists the count and **Delete** stays disabled.",
          "For leaf categories: note that products still linked must be reassigned before deletion succeeds.",
          "Click **Delete** to confirm, or **Cancel** to keep the category.",
        ],
        tips: [
          "Delete subcategories first, then the main category — the API blocks deleting parents with children.",
          "Empty categories with no products delete immediately; product-linked categories may return an error toast.",
        ],
        stepHighlights: ["table-actions", "delete-action", "delete-dialog", "delete-dialog", "delete-dialog"],
        preview: "list",
      },
    ],
  },
  {
    key: "inventory",
    label: "Inventory",
    icon: "Archive",
    section: "Products",
    audience: "staff",
    intro:
      "Track every stock movement for the selected branch: manual adjustments, order fulfilment, and product changes. Filter the log, watch **Low Stock** alerts, adjust quantities, and export to Excel.",
    screens: [
      {
        id: "inventory-list",
        title: "Movement history",
        route: "/inventory",
        permission: "view",
        summary:
          "Paginated log of all stock in, stock out, and adjustment entries — filtered by date, category, movement type, and source.",
        steps: [
          "Open **Inventory** from the sidebar (Products section). Stock is scoped to the **branch** selected in the header.",
          "Review the page header — **Export to Excel** downloads reports; **Adjust Stock** opens the manual adjustment dialog.",
          "Use **Date range** to limit log entries to a period (created date of each movement).",
          "Filter by **Category**, **All Movements** (Stock In / Stock Out / Adjustments), or **All Sources** (Manual, Order, Product, Variant, Other).",
          "Read the movement table: **Date**, **Product** (with variant if applicable), **Type** badge, **Source**, **Updated by**, **Quantity** (+/−), **Notes**.",
          "Use pagination at the bottom to browse older log pages (10 entries per page).",
        ],
        tips: [
          "Order fulfilment creates automatic **Stock Out** entries — notes usually reference the order number.",
          "Source badges are derived from notes — manual restocks show **Manual**, system order deductions show **Order**.",
        ],
        stepHighlights: [
          "page-header",
          "page-header",
          "filter-date-range",
          "filters",
          "data-table",
          "data-table",
        ],
        preview: "list",
      },
      {
        id: "inventory-low-stock",
        title: "Low stock alerts",
        route: "/inventory",
        permission: "view",
        summary:
          "Toggle the Low Stock button to swap the log for a red alert panel listing products at or below their threshold.",
        steps: [
          "On the inventory page, click the **Low Stock** button in the filter bar (shows a count badge when items are low).",
          "The movement log hides and the **Low Stock Alerts** panel appears with a red header.",
          "Each row shows **Product**, **SKU**, **Current stock** (red badge), and **Threshold** from product settings.",
          "Click **Restock** on a row to open **Adjust Inventory** with that product pre-selected (Stock In).",
          "Use the **Adjust Stock** button in the low-stock table header for a blank adjustment dialog.",
          "Click **Low Stock** again to return to the movement history view.",
        ],
        tips: [
          "Low-stock thresholds are set on each product under **Pricing & stock** / **Stock alerts** in Products.",
          "The badge count turns red when low-stock items exist but the panel is collapsed.",
        ],
        stepHighlights: [
          "filter-low-stock",
          "low-stock-panel",
          "low-stock-table",
          "restock-action",
          "low-stock-table",
          "filter-low-stock",
        ],
        preview: "list",
      },
      {
        id: "inventory-adjust",
        title: "Adjust stock",
        route: "/inventory",
        permission: "edit",
        summary:
          "Manually record Stock In, Stock Out, or Adjustment for a product (and variant if applicable) at the current branch.",
        steps: [
          "Click **Adjust Stock** in the page header, **Restock** on a low-stock row, or the header button inside the low-stock table.",
          "The **Adjust Inventory** dialog opens — pick **Product** and **Variant** (required when the product has variants).",
          "Choose **Movement Type**: **Stock In (+)** adds units, **Stock Out (−)** removes units, **Adjustment (+/−)** for corrections.",
          "Enter **Quantity** — must be a positive number; direction comes from the movement type.",
          "Add **Notes / Reason** — e.g. Restock, Damaged goods, Physical count (also used to classify source in the log).",
          "Click **Save Adjustment** — stock updates immediately, a new log row appears, and low-stock alerts refresh.",
          "**Cancel** closes the dialog without changing stock.",
        ],
        tips: [
          "Stock Out fails if quantity exceeds available stock at this branch — you'll see an error toast.",
        ],
        stepHighlights: [
          "header-action-adjust",
          "adjust-dialog",
          "product-variant-select",
          "movement-type",
          "adjust-quantity",
          "adjust-notes",
          "form-save",
          "form-cancel",
        ],
        preview: "form",
      },
      {
        id: "inventory-export",
        title: "Export to Excel",
        route: "/inventory",
        permission: "view",
        summary:
          "Download movement history and optional current stock snapshot as a multi-sheet .xlsx file.",
        steps: [
          "Click **Export to Excel** in the inventory page header (requires **Inventory → View**).",
          "The export dialog opens — choose **Branch** (defaults to header branch) and **Movement type** filter.",
          "Set **Category** to limit rows to one product category, or leave as All.",
          "Toggle **Include current stock sheet** — adds a second sheet with branch stock levels.",
          "Optionally enable **Stock sheet: low stock only** (requires include stock) to export only alert items.",
          "Set the **Date filter** for movements — All dates exports full history; custom range limits the log sheet only.",
          "Click **Export** — file downloads with movement count and stock row count in the success toast.",
        ],
        tips: [
          "List-page filters (date, category, movement type) pre-fill the export dialog when you open it.",
          "Movement date filter does not affect the stock snapshot sheet — only the movements sheet.",
        ],
        stepHighlights: [
          "header-action-export",
          "export-dialog",
          "export-branch",
          "export-category",
          "export-options",
          "export-date-filter",
          "export-save",
        ],
        preview: "form",
      },
    ],
  },
  {
    key: "invoices",
    label: "Invoices",
    icon: "FileText",
    section: "Sales & billing",
    audience: "staff",
    intro: "View GST and non-GST invoices generated from orders.",
    screens: [
      {
        id: "invoices-list",
        title: "Invoices list",
        route: "/invoices",
        permission: "view",
        summary: "Browse invoices with search and date filters.",
        steps: [
          "Open **Invoices** from Sales & billing.",
          "Search by invoice number, order number, or customer.",
          "Filter by date range or GST type.",
          "Click a row to view invoice details and download PDF if available.",
        ],
        preview: "list",
      },
    ],
  },
  {
    key: "payments",
    label: "Payments",
    icon: "CreditCard",
    section: "Sales & billing",
    audience: "staff",
    intro:
      "Track customer payments against orders: browse payment history, see **Due** balances, schedule **Follow Ups**, and record payments from the Payments page or an order detail screen.",
    screens: [
      {
        id: "payments-list",
        title: "All payments",
        route: "/payments",
        permission: "view",
        summary:
          "**All Payments** tab — paginated history with date, order, customer, branch, payment mode, and amount.",
        steps: [
          "Open **Payments** from the sidebar (Sales & billing).",
          "Use the **Branch** dropdown in the header to filter by branch or view all branches.",
          "Select the **All Payments** tab (default) to see recorded payment entries.",
          "Filter with **Date range**, **Category**, or **All Orders** to narrow to one order.",
          "Review the table: **Date**, **Order #**, **Customer**, **Branch**, **Payment Mode** (Cheque shows instrument #), **Amount (₹)** in green.",
          "Use pagination at the bottom to browse older payments (10 per page).",
        ],
        tips: [
          "Payment amounts are always positive in the list — they represent money received against orders.",
          "Click **Record Payment** in the header to add a new entry (requires **Payments → Add**).",
        ],
        stepHighlights: [
          "page-header",
          "branch-selector",
          "payment-tabs",
          "filters",
          "data-table",
          "data-table",
        ],
        preview: "list",
      },
      {
        id: "payments-due",
        title: "Due balances",
        route: "/payments",
        permission: "view",
        summary:
          "**Due** tab — orders with remaining balance (Due or Partially paid status) for the selected branch and filters.",
        steps: [
          "On the Payments page, click the **Due** tab.",
          "Apply **Date range** and **Category** filters to limit which orders appear.",
          "Read **Orders With Due Amount** — badge shows count of due orders.",
          "Each row: **Order #**, **Customer**, **Order date**, **Branch**, **Total**, **Paid** (green), **Remaining** (red).",
          "Use this list to identify who owes money before calling or recording payment.",
          "Record payment via **Record Payment** button or from the order detail page.",
        ],
        tips: [
          "Only orders with pending payment status and remaining balance > ₹0 appear here.",
          "Remaining = Total order amount minus sum of all recorded payments.",
        ],
        stepHighlights: [
          "payment-tabs",
          "due-filters",
          "due-table",
          "due-table",
          "due-table",
          "header-action-record",
        ],
        preview: "list",
      },
      {
        id: "payments-followups",
        title: "Payment follow-ups",
        route: "/payments",
        permission: "view",
        summary:
          "**Follow Ups** tab — overdue and due-today reminders plus a date-wise calendar of scheduled follow-up notes.",
        steps: [
          "Click the **Follow Ups** tab on the Payments page.",
          "Review **Pending reminders** — **Overdue** (red) and **Due today** (amber) cards with order link, balance, and note.",
          "Each card shows follow-up date, payment status badge, due amount, order #, customer, and who created the note.",
          "Scroll to **Follow-ups by date** — pick a date to see all follow-ups scheduled for that day.",
          "Follow-ups only apply to orders with due or partially paid status.",
          "Schedule new follow-ups from the **order detail** page using the Payment Follow-ups panel.",
        ],
        tips: [
          "Overdue reminders are follow-ups whose date has passed — action them first.",
          "Click the order number link on a card to open the order and record payment or add another follow-up.",
        ],
        stepHighlights: [
          "payment-tabs",
          "followups-reminders",
          "followups-reminders",
          "followups-by-date",
          "followup-date-picker",
          "followups-by-date",
        ],
        preview: "list",
      },
      {
        id: "payments-record",
        title: "Record payment",
        route: "/payments",
        permission: "add",
        summary:
          "Record Payment dialog — pick an order with balance due, enter amount/mode, optional notes; updates order payment status.",
        steps: [
          "On the Payments page, click **Record Payment** in the header.",
          "In the dialog, open the **Order** combobox — search by order number or customer; only orders with remaining balance are listed.",
          "After selecting an order, the summary shows **Total**, **Already Paid**, and **Due Amount**.",
          "Enter **Amount (₹)** — whole rupees only; cannot exceed the remaining due amount.",
          "Choose **Payment Mode**: Cash, Bank Transfer, UPI, or Cheque — **Cheque number** field appears for cheque payments.",
          "Add optional **Notes** — transaction ID, UTR, reference, etc.",
          "Click **Record Payment** — the entry appears in All Payments and the order's paid/due totals update.",
          "**Cancel** closes the dialog without saving.",
        ],
        tips: [
          "Selecting an order auto-fills amount with the full remaining balance — you can lower it for partial payments.",
        ],
        stepHighlights: [
          "header-action-record",
          "payment-dialog",
          "order-picker",
          "order-due-summary",
          "payment-amount",
          "payment-mode",
          "payment-notes",
          "form-save",
          "form-cancel",
        ],
        preview: "form",
      },
      {
        id: "payments-record-order",
        title: "Record from order",
        route: "/orders/1042",
        permission: "add",
        summary:
          "Record payment inline on the order detail page — same modes as Payments page, with payment history cards below.",
        steps: [
          "Open an order with due or partially paid status from **Orders** or a follow-up link.",
          "Check the **Payment summary** sidebar — Total, Paid, Due Amount, and Payment status.",
          "In **Record payment**, enter **Amount (whole ₹)**, select **Payment mode**, and optional note.",
          "For **Cheque**, enter the cheque number before submitting.",
          "Click **Add payment** — the new entry appears in the payment history list below.",
          "Review past payments as cards: date, sequence (Advanced / 1st payment), amount, mode, recorded by, and note.",
          "Use **Payment Follow-ups** below to schedule a reminder date and note while balance remains.",
        ],
        tips: [
          "Requires **Payments → Add** permission — the section is hidden without it.",
          "Remaining balance updates immediately after each successful payment.",
        ],
        stepHighlights: [
          "order-payment-summary",
          "order-record-payment",
          "payment-amount",
          "payment-mode",
          "form-save",
          "payment-history",
          "order-followup-panel",
        ],
        preview: "form",
      },
    ],
  },
  {
    key: "reports",
    label: "Reports",
    icon: "BarChart3",
    section: "Sales & billing",
    audience: "staff",
    intro:
      "Analyse revenue, received amounts, and outstanding dues — filter by year, month, branch, and category. Export revenue CSV tables or full order details to Excel.",
    screens: [
      {
        id: "reports-overview",
        title: "Reports overview",
        route: "/reports",
        permission: "view",
        summary:
          "Revenue Reports dashboard — KPI cards (Overall, Received, Due), filters, and both revenue tables on one page.",
        steps: [
          "Open **Reports** from the sidebar (Sales & billing).",
          "Read the page title **Revenue Reports** — revenue, received, and due analysis with category breakdown.",
          "Review the three **KPI cards**: **Overall Revenue** (gradient), **Received** (green progress), **Due** (red progress).",
          "Use the filter bar: **Monthly/Yearly** view, **Month**, **Year**, **Category**, and **Branch** — badges show active view.",
          "Scroll to **Year / Month Revenue** table — revenue, received, due, and order count per period.",
          "Below that, **Category-wise Revenue** matrix shows revenue by product category across periods.",
        ],
        tips: [
          "All totals and tables refresh when you change filters — data comes from `/api/reports/revenue-summary`.",
          "**Export to Excel** in the header exports order rows, not the revenue summary tables.",
        ],
        stepHighlights: [
          "page-header",
          "kpi-cards",
          "kpi-cards",
          "report-filters",
          "revenue-table",
          "category-table",
        ],
        preview: "reports",
      },
      {
        id: "reports-revenue",
        title: "Year / month revenue",
        route: "/reports",
        permission: "view",
        summary:
          "Monthly or yearly revenue table — compare Revenue, Received, Due, and Orders per period; export as CSV.",
        steps: [
          "Set **View by** to **Monthly** (default) or **Yearly** — yearly mode hides the month picker and shows all months.",
          "Pick **Year** (or All years) and optionally **Month** — when both year and a specific month are set, the table switches to daily rows.",
          "Filter by **Category** or **Branch** to scope revenue to one product category or showroom.",
          "Read **Year / Month Revenue** columns: **Year**, **Month**, **Revenue**, **Received** (green), **Due** (red), **Orders**.",
          "Watch the badge — **Monthly view active** or **Daily view active** when a single month is selected.",
          "Click **Export CSV** on this card to download the visible table (daily or monthly format).",
        ],
        tips: [
          "Received + Due should align with order payment totals for the filtered period.",
          "Yearly view aggregates all months in the selected year(s).",
        ],
        stepHighlights: [
          "filter-view-mode",
          "filter-year",
          "filter-category",
          "revenue-table",
          "view-mode-badges",
          "revenue-export-csv",
        ],
        preview: "reports",
      },
      {
        id: "reports-daily",
        title: "Daily revenue view",
        route: "/reports",
        permission: "view",
        summary:
          "When **Monthly** view + a specific **Year** and **Month** are selected, the revenue table shows one row per day.",
        steps: [
          "In filters, keep **View by** as **Monthly** (not Yearly).",
          "Select a **Year** (e.g. 2026) — do not leave as All years.",
          "Choose a specific **Month** (not All months) — this activates **Daily view active**.",
          "The table title changes to **Daily Revenue (Selected Month)**.",
          "Columns become **Date**, **Day**, **Revenue**, **Received**, **Due**, **Orders** — one row per calendar day.",
          "Use **Export CSV** to download daily breakdown for that month.",
        ],
        tips: [
          "Daily view is ideal for spotting high-sales days within a month.",
          "Selecting All months returns to the year/month aggregated table.",
        ],
        stepHighlights: [
          "filter-view-mode",
          "filter-month",
          "filter-year",
          "view-mode-badges",
          "revenue-table",
          "revenue-export-csv",
        ],
        preview: "reports",
      },
      {
        id: "reports-category",
        title: "Category-wise revenue",
        route: "/reports",
        permission: "view",
        summary:
          "Pivot-style matrix — categories as columns, periods as rows, plus a Total row; export as CSV.",
        steps: [
          "Scroll to the **Category-wise Revenue** card at the bottom of the Reports page.",
          "First column is **Month** (or **Date** in daily view) — one row per period in your filter.",
          "Category columns show revenue attributed to each order's **Order category** (not line-item products).",
          "Empty cells show **—**; amounts use Indian rupee formatting.",
          "The **Total** row sums each category column for the filtered range.",
          "Click **Export CSV** to download the matrix (header row = period label + category names).",
        ],
        tips: [
          "Category matrix period granularity matches your filter — days when daily view is active, months otherwise.",
          "Use category filter above to focus the entire page on one category.",
        ],
        stepHighlights: [
          "category-table",
          "category-table",
          "category-table",
          "category-table",
          "category-table",
          "category-export-csv",
        ],
        preview: "reports",
      },
      {
        id: "reports-export-orders",
        title: "Export orders to Excel",
        route: "/reports",
        permission: "view",
        summary:
          "**Export to Excel** in the page header — download full order details (not revenue summary) as .xlsx.",
        steps: [
          "Click **Export to Excel** in the top-right of the Reports page.",
          "The **Export Orders to Excel** dialog opens — separate from the revenue table CSV buttons.",
          "Set **Date filter**: All dates, Year, Month, or Custom range (start + end required for custom).",
          "Choose **Branch** (defaults to header branch) and **Category** to limit exported orders.",
          "Click **Export** — orders matching filters download as Excel with full order details.",
          "Cancel closes without downloading.",
        ],
        tips: [
          "Revenue table **Export CSV** buttons export summary tables only; this dialog exports individual order rows.",
          "Success toast shows how many orders were exported.",
        ],
        stepHighlights: [
          "header-action-export-orders",
          "orders-export-dialog",
          "export-date-filter",
          "export-branch",
          "export-category",
          "export-save",
        ],
        preview: "reports",
      },
    ],
  },
  {
    key: "tools",
    label: "Curtain calculator",
    icon: "Calculator",
    section: "Tools",
    audience: "all",
    intro: "Estimate curtain fabric and pricing for customer quotes.",
    screens: [
      {
        id: "curtain-calculator",
        title: "Curtain calculator",
        route: "/curtain-calculator",
        permission: "view",
        summary: "Enter window dimensions and fabric options to get estimates.",
        steps: [
          "Open **Curtain calculator** from Tools.",
          "Enter width, height, fullness, and fabric rate.",
          "Review calculated meters and estimated price.",
          "Use the result when creating a quote or order.",
        ],
        preview: "calculator",
      },
    ],
  },
  {
    key: "suppliers",
    label: "Suppliers",
    icon: "Building2",
    section: "Procurement",
    audience: "staff",
    intro:
      "Maintain supplier companies used in **Purchase Orders** — contact details, GST, and a **Supplier Portal** login (mobile + password).",
    screens: [
      {
        id: "suppliers-list",
        title: "Suppliers list",
        route: "/suppliers",
        permission: "view",
        summary: "Searchable table of suppliers with contact, GST, and Active/Inactive status.",
        steps: [
          "Open **Suppliers** from the sidebar (Procurement section).",
          "Review the page header and **Add Supplier** button (requires **Suppliers → Add**).",
          "Use **Search suppliers…** to filter by company name, contact, or mobile.",
          "Scan the table: **Name**, **Contact Person**, **Mobile**, **GST Number**, **Status** badge.",
          "Use **Edit** (pencil) or **Delete** (trash) on each row when your role allows.",
          "Pagination shows 10 suppliers per page when the list is long.",
        ],
        tips: [
          "Suppliers appear in PO vendor pickers once created.",
          "Inactive suppliers may still exist in historical PO records.",
        ],
        stepHighlights: ["page-header", "search", "data-table", "table-actions", "table-actions", "data-table"],
        preview: "list",
      },
      {
        id: "suppliers-create",
        title: "Add supplier",
        route: "/suppliers",
        permission: "add",
        summary: "Create a supplier and its portal login via dialog — portal password and mobile required on create.",
        steps: [
          "Click **Add Supplier** in the page header.",
          "Enter **Company Name*** — legal or trading name.",
          "Fill **Contact Person** and **Mobile Number** — mobile is required to create the portal login.",
          "Set **Supplier Portal Password*** — creates the supplier portal user for Procurement.",
          "Optionally add **Email**, **GST Number** (15-character GSTIN), and **Address**.",
          "Click **Create Supplier** — the list refreshes and the partner can log into the supplier portal with mobile + password.",
        ],
        tips: [
          "Duplicate mobile or email may return a server conflict error on the matching field.",
          "Portal password is not shown again after save — share it securely with the supplier.",
        ],
        stepHighlights: [
          "header-action-add",
          "partner-dialog",
          "company-name",
          "contact-mobile",
          "portal-password",
          "gst-number",
          "address-field",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "suppliers-edit",
        title: "Edit supplier",
        route: "/suppliers",
        permission: "edit",
        summary: "Update supplier details or reset portal password from the list dialog.",
        steps: [
          "Click the **Edit** (pencil) icon on a supplier row.",
          "The **Edit Supplier** dialog loads existing company and contact fields.",
          "Update **Company Name**, contact details, **Email**, **GST**, or **Address** as needed.",
          "To reset portal access, enter a new **Supplier Portal Password** — requires **Mobile Number** on the record.",
          "Leave password blank to keep the current portal password unchanged.",
          "Click **Update Supplier** to save.",
        ],
        stepHighlights: [
          "table-actions",
          "partner-dialog",
          "company-name",
          "contact-person",
          "portal-password",
          "gst-number",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "suppliers-delete",
        title: "Delete supplier",
        route: "/suppliers",
        permission: "delete",
        summary: "Remove a supplier after browser confirmation.",
        steps: [
          "Click the red **Delete** (trash) icon on a supplier row.",
          "Confirm **Are you sure you want to delete this supplier?** in the browser dialog.",
          "Deletion succeeds only if the supplier is not linked to blocking records — otherwise an error toast appears.",
        ],
        tips: ["Prefer marking inactive (if supported by admin) over delete when historical POs exist."],
        stepHighlights: ["table-actions", "delete-action", "delete-dialog"],
        preview: "list",
      },
    ],
  },
  {
    key: "manufacturers",
    label: "Manufacturers",
    icon: "Factory",
    section: "Procurement",
    audience: "staff",
    intro:
      "Manage custom furniture manufacturers — specialization, contact info, and **Manufacturer Portal** login for PO collaboration.",
    screens: [
      {
        id: "manufacturers-list",
        title: "Manufacturers list",
        route: "/manufacturers",
        permission: "view",
        summary: "Searchable table with contact, specialization, and Active/Inactive status.",
        steps: [
          "Open **Manufacturers** from the sidebar (Procurement section).",
          "Use **Add Manufacturer** in the header to create a new partner (requires **Manufacturers → Add**).",
          "Search with **Search manufacturers…** by name, contact, or mobile.",
          "Review columns: **Name**, **Contact Person**, **Mobile**, **Specialization**, **Status**.",
          "Use row **Edit** or **Delete** actions when permitted.",
        ],
        stepHighlights: ["page-header", "header-action-add", "search", "data-table", "table-actions"],
        preview: "list",
      },
      {
        id: "manufacturers-create",
        title: "Add manufacturer",
        route: "/manufacturers",
        permission: "add",
        summary: "Dialog form with company details, specialization, and required portal password on create.",
        steps: [
          "Click **Add Manufacturer** in the page header.",
          "Enter **Company Name*** and contact fields — **Mobile** required for portal login.",
          "Set **Email** and **Specialization** (e.g. Wood, Metal, Upholstery) to describe their work.",
          "Add **Address** if needed for records or dispatch.",
          "Set **Manufacturer Portal Password*** — creates the manufacturer portal user.",
          "Click **Create Manufacturer** — partner can sign in to the manufacturer portal with mobile + password.",
        ],
        stepHighlights: [
          "header-action-add",
          "partner-dialog",
          "company-name",
          "contact-person",
          "specialization",
          "address-field",
          "portal-password",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "manufacturers-edit",
        title: "Edit manufacturer",
        route: "/manufacturers",
        permission: "edit",
        summary: "Update manufacturer profile or reset portal password.",
        steps: [
          "Click **Edit** on a manufacturer row.",
          "Update **Company Name**, **Contact Person**, **Mobile**, **Email**, **Specialization**, or **Address**.",
          "Enter **Manufacturer Portal Password** only to reset login — leave blank to keep current password.",
          "Mobile must be present if you set a new portal password.",
          "Click **Update Manufacturer**.",
        ],
        stepHighlights: [
          "table-actions",
          "partner-dialog",
          "company-name",
          "specialization",
          "portal-password",
          "form-save",
        ],
        preview: "form",
      },
      {
        id: "manufacturers-delete",
        title: "Delete manufacturer",
        route: "/manufacturers",
        permission: "delete",
        summary: "Remove a manufacturer after confirmation.",
        steps: [
          "Click the **Delete** (trash) icon on a row.",
          "Confirm deletion in the browser prompt.",
          "If linked POs or portal users block deletion, you'll see an error toast instead.",
        ],
        stepHighlights: ["table-actions", "delete-action", "delete-dialog"],
        preview: "list",
      },
    ],
  },
  {
    key: "branches",
    label: "Branches",
    icon: "GitBranch",
    section: "Administration",
    audience: "staff",
    intro: "Configure showroom and warehouse branches.",
    screens: crudScreens(
      "branches",
      "Branch",
      "/branches",
      "/branches",
      "/branches",
      "/branches",
      "Branch",
    ).map((s) =>
      s.id.includes("create") || s.id.includes("edit")
        ? { ...s, route: "/branches" }
        : s,
    ),
  },
  {
    key: "users",
    label: "Users",
    icon: "Users",
    section: "Administration",
    audience: "staff",
    intro: "Manage staff accounts, roles, and branch assignments.",
    screens: [
      {
        id: "users-list",
        title: "Users list",
        route: "/users",
        permission: "view",
        summary: "Browse staff users with role and branch filters.",
        steps: [
          "Open **Users** under Administration.",
          "Search by name, email, or mobile.",
          "Filter by role or branch.",
          "Review active/inactive status badges.",
        ],
        preview: "list",
      },
      {
        id: "users-add",
        title: "Add user",
        route: "/users",
        permission: "add",
        summary: "Create a new staff account with role and branches.",
        steps: [
          "Click **Add user**.",
          "Enter name, mobile, email, and temporary password.",
          "Assign a role — permissions come from that role.",
          "Select one or more branches and save.",
        ],
        preview: "form",
      },
      {
        id: "users-edit",
        title: "Edit user",
        route: "/users",
        permission: "edit",
        summary: "Update user details, role, or branch access.",
        steps: [
          "Click **Edit** on a user row.",
          "Update fields — leave password blank to keep the current one.",
          "Toggle active status or sales scope if shown.",
          "Save changes.",
        ],
        preview: "form",
      },
      {
        id: "users-delete",
        title: "Delete user",
        route: "/users",
        permission: "delete",
        summary: "Remove a user after password confirmation.",
        steps: [
          "Click **Delete** on a user.",
          "Enter your password in the confirmation dialog.",
          "Confirm deletion.",
        ],
        preview: "list",
      },
    ],
  },
  {
    key: "roles",
    label: "Roles & permissions",
    icon: "ShieldCheck",
    section: "Administration",
    audience: "staff",
    intro: "Define roles and control module access (view, add, edit, delete).",
    screens: [
      {
        id: "roles-list",
        title: "Roles list",
        route: "/roles",
        permission: "view",
        summary: "View all roles and how many permissions each grants.",
        steps: [
          "Open **Roles** under Administration.",
          "See role name and permission summary for each row.",
          "Click a role to view or edit its permission matrix.",
        ],
        preview: "list",
      },
      {
        id: "roles-add",
        title: "Create role",
        route: "/roles",
        permission: "add",
        summary: "Add a new role with a custom permission matrix.",
        steps: [
          "Click **Add role**.",
          "Enter role name.",
          "Check view/add/edit/delete for each module row.",
          "Save — assign this role to users on the Users page.",
        ],
        tips: ["This guide shows only modules your own role can access."],
        preview: "form",
      },
      {
        id: "roles-edit",
        title: "Edit role permissions",
        route: "/roles",
        permission: "edit",
        summary: "Change what a role can do across modules.",
        steps: [
          "Open a role and update permission checkboxes.",
          "Save — all users with that role get the updated access immediately.",
        ],
        preview: "form",
      },
      {
        id: "roles-delete",
        title: "Delete role",
        route: "/roles",
        permission: "delete",
        summary: "Remove an unused role.",
        steps: [
          "Click **Delete** on a role.",
          "Confirm — roles assigned to users cannot be deleted until reassigned.",
        ],
        preview: "list",
      },
    ],
  },
  {
    key: "activityLogs",
    label: "Activity logs",
    icon: "ScrollText",
    section: "Administration",
    audience: "staff",
    intro: "Audit trail of important actions across the system.",
    screens: [
      {
        id: "activity-logs-list",
        title: "Activity logs",
        route: "/activity-logs",
        permission: "view",
        summary: "Review who did what and when.",
        steps: [
          "Open **Activity logs** under Administration.",
          "Filter by user, module, or date range.",
          "Read action descriptions and timestamps for compliance and troubleshooting.",
        ],
        tips: ["Access is limited to Super Admin or users with Activity logs view permission."],
        preview: "list",
      },
    ],
  },
  {
    key: "complaints",
    label: "Complaints & support",
    icon: "Headphones",
    section: "General",
    audience: "all",
    intro: "Raise and track customer or partner support tickets.",
    screens: [
      {
        id: "complaints-list",
        title: "Complaints list",
        route: "/complaints",
        permission: "view",
        summary: "View open and closed support tickets.",
        steps: [
          "Open **Complaints** from the General section.",
          "Filter by status, assignee, or search by subject.",
          "Click a row to open complaint details.",
        ],
        preview: "list",
      },
      {
        id: "complaints-create",
        title: "Raise complaint",
        route: "/complaints",
        permission: "add",
        summary: "Create a new support ticket linked to an order or PO.",
        steps: [
          "Click **New complaint**.",
          "Enter subject, description, and link to order/PO if applicable.",
          "Submit — assignees get notified.",
        ],
        preview: "form",
      },
      {
        id: "complaints-detail",
        title: "Complaint details",
        route: "/complaints/41",
        permission: "view",
        summary: "Follow conversation and status updates.",
        steps: [
          "Open a complaint from the list.",
          "Read timeline, comments, and current status.",
          "Check assignee and linked records.",
        ],
        preview: "detail",
      },
      {
        id: "complaints-update",
        title: "Update complaint status",
        route: "/complaints/41",
        permission: "edit",
        summary: "Change status or add responses.",
        steps: [
          "Open the complaint detail page.",
          "Update status or add a reply if you are the assignee or admin.",
          "Save — requester sees the update.",
        ],
        tips: ["Only assigned users or Super Admin can change status in most cases."],
        preview: "form",
      },
      {
        id: "complaints-delete",
        title: "Delete complaint",
        route: "/complaints",
        permission: "delete",
        summary: "Remove a complaint record.",
        steps: ["Click **Delete** and confirm."],
        preview: "list",
      },
    ],
  },
  {
    key: "settings",
    label: "Settings",
    icon: "Settings",
    section: "General",
    audience: "all",
    intro: "Company profile and application preferences.",
    screens: [
      {
        id: "settings-view",
        title: "View settings",
        route: "/settings",
        permission: "view",
        summary: "See company name, logo, contact, and tax settings.",
        steps: [
          "Open **Settings** from the General section.",
          "Review company details and invoice configuration.",
        ],
        preview: "settings",
      },
      {
        id: "settings-edit",
        title: "Edit company settings",
        route: "/settings",
        permission: "edit",
        summary: "Update company profile and billing configuration.",
        steps: [
          "Edit fields on the settings form.",
          "Upload logo or update GST details if shown.",
          "Click **Save** — changes apply to new invoices and documents.",
        ],
        preview: "form",
      },
    ],
  },
];

/** Partner portal (supplier / manufacturer) guide content. */
export const PARTNER_GUIDE_MODULES: GuideModule[] = [
  {
    key: "dashboard",
    label: "Partner dashboard",
    icon: "LayoutDashboard",
    section: "Portal",
    audience: "partner",
    intro: "Overview of purchase orders and notifications for your organization.",
    screens: [
      {
        id: "partner-dashboard",
        title: "Portal dashboard",
        route: "/dashboard",
        permission: "view",
        summary: "See pending POs, recent activity, and quick stats.",
        steps: [
          "Log in with your supplier or manufacturer portal account.",
          "Review summary cards for open purchase orders.",
          "Use quick links to open PO list or notifications.",
        ],
        preview: "dashboard",
      },
    ],
  },
  {
    key: "purchaseOrders",
    label: "Purchase orders",
    icon: "ClipboardList",
    section: "Portal",
    audience: "partner",
    intro: "View and respond to purchase orders from MGR Casa.",
    screens: [
      {
        id: "partner-po-list",
        title: "PO list",
        route: "/purchase-orders",
        permission: "view",
        summary: "All POs sent to your organization.",
        steps: [
          "Open **Purchase orders** from the sidebar.",
          "Filter by status or search by PO number.",
          "Click a row to open details.",
        ],
        preview: "list",
      },
      {
        id: "partner-po-detail",
        title: "PO details",
        route: "/purchase-orders/1042",
        permission: "view",
        summary: "Line items, quantities, rates, and delivery expectations.",
        steps: [
          "Open a PO from the list.",
          "Review items, totals, and requested delivery date.",
          "Check status and any linked complaints.",
        ],
        preview: "detail",
      },
      {
        id: "partner-po-update",
        title: "Confirm or update PO",
        route: "/purchase-orders/1042",
        permission: "edit",
        summary: "Accept PO, update status, or add fulfillment notes.",
        steps: [
          "Open the PO detail page.",
          "Update status (e.g. Confirmed, In production) when allowed.",
          "Add notes or expected dispatch date.",
          "Save — MGR Casa staff see your updates.",
        ],
        preview: "form",
      },
    ],
  },
  {
    key: "products",
    label: "Products",
    icon: "Package",
    section: "Portal",
    audience: "partner",
    intro: "View product details referenced in your purchase orders.",
    screens: [
      {
        id: "partner-product-detail",
        title: "Product details",
        route: "/products/501",
        permission: "view",
        summary: "Read-only product information from catalog.",
        steps: [
          "Open a product link from a PO line item.",
          "Review SKU, description, and specifications.",
        ],
        preview: "detail",
      },
    ],
  },
  {
    key: "complaints",
    label: "Complaints",
    icon: "Headphones",
    section: "General",
    audience: "partner",
    intro: "Support tickets related to your POs.",
    screens: STAFF_GUIDE_MODULES.find((m) => m.key === "complaints")!.screens.filter((s) =>
      ["complaints-list", "complaints-detail", "complaints-update"].includes(s.id),
    ),
  },
  {
    key: "settings",
    label: "Settings",
    icon: "Settings",
    section: "General",
    audience: "partner",
    intro: "Your portal profile and notification preferences.",
    screens: [
      {
        id: "partner-settings",
        title: "Portal settings",
        route: "/settings",
        permission: "view",
        summary: "View and update your account settings.",
        steps: [
          "Open **Settings** from the General section.",
          "Update contact details or password if available.",
        ],
        preview: "settings",
      },
    ],
  },
];

export const GUIDE_INTRO = {
  title: "User guide",
  subtitle: "Step-by-step help for every screen you can access",
  description:
    "This guide adapts to your role. You only see modules and actions your permissions allow — for example, if you can view orders but not create them, you will see list and detail guides without the create-order section.",
};
